baseurl = "/"
languageCode = "en-us"
title = "Homepage"
theme = "nofancy"

[params]
    highlight="Assign a syntax highlight style"

[author]
    name = "i_love_code"
    github = "i-love-code"
    gaID = "UA-116671531-1"
    twitter = "i-luv-code"